"""Build data.js for the demo video from real recordings. No GPU needed.

  venv/bin/python bench/demo/build_data.py \
      --single ~/bench/demo/baseline.json ~/bench/demo/dflash2.json \
      --tokenizer models/Qwen3.8-27B-W4A16-AutoRound-fast/tokenizer.json \
      --batch results/batch_128_512.log \
      --out bench/demo/data.js

Single request: two demo_capture.py recordings, each streamed chunk with the time it
arrived. A chunk is not a token -- DFlash2 delivers a whole accepted run in one SSE
event -- so the full text is tokenized once and every token is assigned to the chunk
its last character arrived in. That count is exact where the old renderer's
character-share split was an estimate, and it is what the video's "tokens per step"
strip draws.

Batch: `vllm bench serve` records no per-token arrivals, only its summary. The video
therefore replays a model of that run, and this file carries the measured figures the
model is fitted to (mean TTFT, mean TPOT, duration, request shape). Every number the
video prints about the batch run comes from here.
"""
import argparse
import bisect
import json
import os
import re

from tokenizers import Tokenizer

ap = argparse.ArgumentParser()
ap.add_argument("--single", nargs=2, metavar=("STOCK", "REPO"), required=True)
ap.add_argument("--tokenizer", required=True)
ap.add_argument("--batch", required=True, help="vllm bench serve log, 64 concurrent 128/512")
ap.add_argument("--batch-date", default="2026-09-23")
ap.add_argument("--single-date", default="2026-08-20")
ap.add_argument("--out", required=True)
a = ap.parse_args()

tk = Tokenizer.from_file(os.path.expanduser(a.tokenizer))


def lane(p):
    texts = [c[1] for c in p["tokens"]]
    ends, acc = [], 0
    for s in texts:
        acc += len(s)
        ends.append(acc)
    enc = tk.encode("".join(texts), add_special_tokens=False)
    counts = [0] * len(texts)
    for _, end in enc.offsets:
        counts[min(bisect.bisect_left(ends, end), len(texts) - 1)] += 1
    # [ms since first token, text, tokens in this chunk]
    return {"chunks": [[c[0], c[1], n] for c, n in zip(p["tokens"], counts)],
            "n_out": p["n_out"], "prompt_tokens": p["prompt_tokens"],
            "ttft_s": p["ttft_s"], "decode_s": p["decode_s"],
            "decode_tok_s": p["decode_tok_s"]}


stock, repo = (json.load(open(os.path.expanduser(f))) for f in a.single)
prompts = []
for ps, pr in zip(stock["prompts"], repo["prompts"]):
    assert ps["key"] == pr["key"]
    prompts.append({"key": ps["key"], "label": ps["label"],
                    "stock": lane(ps), "repo": lane(pr)})

log = open(os.path.expanduser(a.batch)).read()


def num(label):
    m = re.search(re.escape(label) + r":\s+([0-9.]+)", log)
    return float(m.group(1))


def arg(name):
    return int(re.search(rf"{name}=(\d+)", log).group(1))


batch = {
    "date": a.batch_date,
    "concurrency": arg("max_concurrency"),
    "requests": arg("num_prompts"),
    "input_len": arg("random_input_len"),
    "output_len": arg("random_output_len"),
    "duration_s": num("Benchmark duration (s)"),
    "output_tok_s": num("Output token throughput (tok/s)"),
    "generated": int(num("Total generated tokens")),
    "mean_ttft_ms": num("Mean TTFT (ms)"),
    "median_ttft_ms": num("Median TTFT (ms)"),
    "p99_ttft_ms": num("P99 TTFT (ms)"),
    "mean_tpot_ms": num("Mean TPOT (ms)"),
    "median_tpot_ms": num("Median TPOT (ms)"),
    "p99_tpot_ms": num("P99 TPOT (ms)"),
}
# The repo's decode convention: concurrency x 1000 / median TPOT.
batch["decode_tok_s"] = round(batch["concurrency"] * 1000 / batch["median_tpot_ms"], 1)

# data.js rather than .json, so index.html also plays straight from disk (file://).
blob = json.dumps({"single": {"date": a.single_date, "prompts": prompts}, "batch": batch},
                  ensure_ascii=False, separators=(",", ":"))
with open(a.out, "w") as f:
    f.write("// generated by build_data.py -- do not edit\nwindow.HQ_DATA = " + blob + ";\n")
print(f"wrote {a.out}: {len(prompts)} prompts; batch {batch['decode_tok_s']} tok/s decode, "
      f"{batch['output_tok_s']} end-to-end over {batch['duration_s']} s")
